spring.config.import=optional:file:Projects_Management_BE/.env[.properties]

server.address=${ADDRESS}
server.port=${PORT}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

#disable swagger
springdoc.swagger-ui.enabled=false
springdoc.api-docs.enabled=false