# Chuy?n sang dùng H2 thay vì MySQL khi ch?y test
spring.datasource.url=jdbc:h2:mem:testdb;MODE=MySQL
spring.datasource.driver-class-name=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
# T?t vi?c yêu c?u script kh?i t?o n?u c?n
spring.sql.init.mode=never